ARG POSTGRES_IMAGE=postgres:16-bookworm
FROM ${POSTGRES_IMAGE}

USER root
RUN test -f "$(pg_config --sharedir)/extension/pg_trgm.control" \
    && test -f "$(pg_config --sharedir)/extension/pgcrypto.control" \
    && mkdir -p /var/lib/postgresql/data /var/run/postgresql \
    && chgrp -R 0 /var/lib/postgresql /var/run/postgresql \
    && chmod -R g=u /var/lib/postgresql /var/run/postgresql
COPY --chmod=0755 init-openvox.sh /docker-entrypoint-initdb.d/10-openvox.sh
ENV PGDATA=/var/lib/postgresql/data/pgdata
USER 999:0
